context:
  name: trunk
  version: "0.21.14"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/trunk-rs/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8687bcf96bdc4decee88458745bbb760ad31dfd109e955cf455c2b64caeeae2f

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: trunk --help

about:
  homepage: https://trunkrs.dev
  summary: Summary of the package.
  description: |
    Build, bundle & ship your Rust WASM application to the web.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://docs.rs/trunk
  repository: https://github.com/trunk-rs/trunk

extra:
  recipe-maintainers:
    - maurosilber
